### ISSUE TITLE
User Experience Enhancement 

### ISSUE THREAD

**Issue by rosalie-baxter** [fac19/hjrv-week2#27]
Would improve user experience if there were clearer instructions for the game - once I figured it out I had fun with it, but took me a min to figure out what I could type into the box initially :sweat_smile:

Perhaps have an instruction like “Find a quote by suggesting a theme” and have some examples of themes as placeholders which you know bring ideas back). https://www.w3schools.com/tags/att_input_placeholder.asp

Along these lines, might be good to have visible error handling for if the api brings no quotes back – something appearing on the screen to explain that this is what has happened.

**Comment by hannahgooding** [comment]
Visible error handling would be great, I started off by searching "hello" and the console logged the error "Response not OK" but without the console I assumed that the game wasn't working on my server.

**Comment by jamesj-0** [comment]
When I tried to select an answer the button hover is red. Is there an indicator for when the correct answer is selected?

**Comment by hannahgooding** [comment]
Also agreed with Rosa about the suggestions of types of word inputs. You have built in some great logic  that specifies the type of user inputs so it would be good to guide the user about these.
