### ISSUE TITLE
Accessibility: Couple easy fixes

### ISSUE THREAD

**Issue by rosalie-baxter** [fac19/hjrv-week2#31]
![accessibility](https://user-images.githubusercontent.com/45801475/76572208-5b2ebc80-64b1-11ea-9e62-b63fa4fd0d89.png)

Think you could make a couple quick changes which would make a big difference - think you've accidentally unmatched the for and id on the input and label 

![formelements](https://user-images.githubusercontent.com/45801475/76572417-ead46b00-64b1-11ea-84df-159d8b19d8f6.png)

**Comment by hannahgooding** [comment]
The Chrome Vox extension is reading out all the button elements when I tab through the page, which is great. Can you make the quote a focusable element so that the containing text is read out?
