### ISSUE TITLE
Enter key on 'Go'

### ISSUE THREAD

**Issue by glrta** [fac19/hjrv-week2#44]
It would be good to have the enter key to work on the search 'Go' button.

**Comment by oliverjam** [comment]
I was just thinking this as well, then the UI suddenly updated! I think the API is just quite slow, so you hit enter and it seems like nothing happens for a bit. #34 should help 😅

**Comment by oliverjam** [comment]
Thanks for fixing 🙏 

It's usually a good idea to associate the commit/PR that closes an issue, so that it pops up here. That way anyone who finds the issue can quickly see what code closed it.

E.g. "relates #44" in the commit message or PR body
